"""
Django settings for wallpaperfactory project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4l6tkl9pbf#*^6wn9$5m^4#l9rnb3jukzjm&k3y3!!oh=k-9*h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

REPORTS_FOLDER = BASE_DIR.joinpath("data", "reports")
CONSTRUCTOR_IMAGES_FOLDER = BASE_DIR.joinpath("data", "constructor")
CONSTRUCTOR_FORMATS = ["jpg", "jpeg", "png"]
MANAGER_GROUP_NAME = "Manager"
ACCOUNTANT_GROUP_NAME = "Accountant"

# Доп. цена за обои при использовании конструктора. (Должна быть выше всех цен
# на дизайны, т.к. пользователь может использовать картинку с дизайна в
# конструкторе)
CONSTRUCTOR_PRICE = 2500

# ID типов доходов в базе данных. Если None, система не будет автоматически
# регистрирвать доход при заказе
INCOME_TYPE_SELL_PREMADE_ID = 1
INCOME_TYPE_SELL_CUSTOM_ID = 2

# Application definition
AUTH_USER_MODEL = 'website.SiteUser'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wallpaperfactory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'website/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'website.context_processors.initial_data',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wallpaperfactory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# print(os.path.join(BASE_DIR, 'databases_data', 'wallpaperfactory.cnf'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wallpaperfactory',
        'USER': 'wallpaperfactory',
        'PASSWORD': '4dCE=Ss=6ed17i0w',
        'HOST': '91.210.171.149',
        'PORT': '3306',
        # 'OPTIONS': {
        #     # 'read_default_file': os.path.join(BASE_DIR, 'databases_data', 'wallpaperfactory.cnf'),
        # },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
